services: 
  go-app:
    container_name: go-app
    image: go-api #image
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go_db

  go_db:
    container_name: go_db #Nome da image
    image: postgres:12 #O banco e a versao
    environment: #variaveis de ambiente do container
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
    volumes: #utilizado para que os datos do database persista mesmo com o container sendo encerrado
     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}